---
apiVersion: v1
kind: Service
metadata:
  name: pyspark-hdfs-jupyter-svc
  namespace: eabraham-373705
spec:
  type: NodePort
  ports:
    - port: 8888
      protocol: TCP
      name: jupyter
    - port: 4040
      protocol: TCP
      name: spark
  selector:
    app: pyspark-hdfs-jupyter-scalables

